apiVersion: v1
kind: Service
metadata:
  name: sim-engine-service
  namespace: baseball-sim
spec:
  selector:
    app: sim-engine
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP