apiVersion: v1
kind: Service
metadata:
  name: data-fetcher-service
  namespace: baseball-sim
spec:
  selector:
    app: data-fetcher
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP