apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: baseball-sim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: baseball-sim/frontend:latest
        imagePullPolicy: Never  # For local k3s, use locally built images
        ports:
        - containerPort: 80
        env:
        - name: API_GATEWAY_URL
          value: "http://api-gateway-service:8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 101  # nginx user
          allowPrivilegeEscalation: false