apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: baseball-sim
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP