apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: baseball-sim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: baseball-sim/api-gateway:latest
        imagePullPolicy: Never  # For local k3s, use locally built images
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgres://baseball_admin:baseball_password@postgres-service:5432/baseball_db?sslmode=disable"
        - name: SIM_ENGINE_URL
          value: "http://sim-engine-service:8081"
        - name: DATA_FETCHER_URL
          value: "http://data-fetcher-service:8082"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false