apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: baseball-sim
data:
  01-scheme.sql: |
    -- Enable required extensions
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

    -- Create schemas
    CREATE SCHEMA IF NOT EXISTS raw_data;
    CREATE SCHEMA IF NOT EXISTS analytics;
    CREATE SCHEMA IF NOT EXISTS simulations;

    -- System information table for metadata
    CREATE TABLE IF NOT EXISTS analytics.system_info (
        key VARCHAR(100) PRIMARY KEY,
        value TEXT NOT NULL,
        description TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    -- Teams table
    CREATE TABLE IF NOT EXISTS teams (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        team_id VARCHAR(10) UNIQUE NOT NULL,
        name VARCHAR(100) NOT NULL,
        abbreviation VARCHAR(5) NOT NULL,
        league VARCHAR(10),
        division VARCHAR(20),
        stadium_id UUID,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    -- Stadiums table with park factors
    CREATE TABLE IF NOT EXISTS stadiums (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        stadium_id VARCHAR(50) UNIQUE NOT NULL,
        name VARCHAR(200) NOT NULL,
        location VARCHAR(200),
        capacity INTEGER,
        dimensions JSONB,
        park_factors JSONB,
        altitude INTEGER,
        surface VARCHAR(50),
        roof_type VARCHAR(50),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    -- Players table
    CREATE TABLE IF NOT EXISTS players (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        player_id VARCHAR(50) UNIQUE NOT NULL,
        first_name VARCHAR(100),
        last_name VARCHAR(100),
        birth_date DATE,
        height INTEGER,
        weight INTEGER,
        bats VARCHAR(1),
        throws VARCHAR(1),
        team_id VARCHAR(10),
        position VARCHAR(5),
        jersey_number INTEGER,
        debut_date DATE,
        active BOOLEAN DEFAULT true,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    -- Games table (partitioned by date for performance)
    CREATE TABLE IF NOT EXISTS games (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        game_id VARCHAR(50) UNIQUE NOT NULL,
        home_team_id VARCHAR(10) NOT NULL,
        away_team_id VARCHAR(10) NOT NULL,
        game_date DATE NOT NULL,
        scheduled_start TIMESTAMP WITH TIME ZONE,
        actual_start TIMESTAMP WITH TIME ZONE,
        game_status VARCHAR(20),
        home_score INTEGER,
        away_score INTEGER,
        inning INTEGER,
        top_bottom VARCHAR(6),
        weather_conditions JSONB,
        stadium_id VARCHAR(50),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    ) PARTITION BY RANGE (game_date);

    -- Create monthly partitions for games (example for 2024)
    CREATE TABLE games_2024_01 PARTITION OF games FOR VALUES FROM ('2024-01-01') TO ('2024-02-01');
    CREATE TABLE games_2024_02 PARTITION OF games FOR VALUES FROM ('2024-02-01') TO ('2024-03-01');
    CREATE TABLE games_2024_03 PARTITION OF games FOR VALUES FROM ('2024-03-01') TO ('2024-04-01');
    CREATE TABLE games_2024_04 PARTITION OF games FOR VALUES FROM ('2024-04-01') TO ('2024-05-01');
    CREATE TABLE games_2024_05 PARTITION OF games FOR VALUES FROM ('2024-05-01') TO ('2024-06-01');
    CREATE TABLE games_2024_06 PARTITION OF games FOR VALUES FROM ('2024-06-01') TO ('2024-07-01');
    CREATE TABLE games_2024_07 PARTITION OF games FOR VALUES FROM ('2024-07-01') TO ('2024-08-01');
    CREATE TABLE games_2024_08 PARTITION OF games FOR VALUES FROM ('2024-08-01') TO ('2024-09-01');
    CREATE TABLE games_2024_09 PARTITION OF games FOR VALUES FROM ('2024-09-01') TO ('2024-10-01');
    CREATE TABLE games_2024_10 PARTITION OF games FOR VALUES FROM ('2024-10-01') TO ('2024-11-01');
    CREATE TABLE games_2024_11 PARTITION OF games FOR VALUES FROM ('2024-11-01') TO ('2024-12-01');
    CREATE TABLE games_2024_12 PARTITION OF games FOR VALUES FROM ('2024-12-01') TO ('2025-01-01');

    -- Essential indexes
    CREATE INDEX IF NOT EXISTS idx_games_date ON games (game_date);
    CREATE INDEX IF NOT EXISTS idx_games_teams ON games (home_team_id, away_team_id);
    CREATE INDEX IF NOT EXISTS idx_players_team ON players (team_id);
    CREATE INDEX IF NOT EXISTS idx_teams_abbrev ON teams (abbreviation);