apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: baseball-sim
type: Opaque
data:
  # echo -n 'baseball_admin' | base64
  POSTGRES_USER: YmFzZWJhbGxfYWRtaW4=
  # echo -n 'baseball_password' | base64  
  POSTGRES_PASSWORD: YmFzZWJhbGxfcGFzc3dvcmQ=
  # echo -n 'baseball_db' | base64
  POSTGRES_DB: YmFzZWJhbGxfZGI=